UKHO/docs

- README.md
- docs/OpenSourceGovernanceChecklist.md
Added the OpenSourceGovernanceChecklist from GitLab
> Add Checklist

- README.md
- docs/OpenGuidance/ContributingDetails.md
- docs/OpenGuidance/OpenGuidance.md
- docs/OpenGuidance/PullRequestDetails.md
- docs/OpenGuidance/ReadmeDetails.md
Moving the open guidance from GitLab onto GitHub
> Add OpenGuidance from GitLab

- CONTRIBUTING.md
- docs/OpenGuidance/ReadmeDetails.md
Also need to remove a link in another file to pass the CI.
> Wording fix to contributing.md

- docs/QualityAssurance/TestCodeStandards.md
- docs/QualityAssurance/TestVision.md
> Add Test Vision and Standards documents

- docs/quality-assurance/test-policy.md
* Added required file extension
* Made minor changes to aid readability
* Added link to ISO 29119
> Update Test Policy document

- docs/quality-assurance/roles/lead-program-test-engineer.md
- docs/quality-assurance/roles/lead-team-test-engineer.md
- docs/quality-assurance/test-profiles.md
- Updated to use Lead (Team) and Lead (Program)
> Ensure correct job roles used in QA roles pages

- docs/quality-assurance/test-strategy.md
Updated following feedback from UKHO developers
> Update Cross Browser testing statement in QA docs

- docs/quality-assurance/test-code-standards.md
* Needed to add text about using Pickles to publish SpecFlow/Cucumber tests if using
> Add SpecFlow/Cucumber section to QA standards

- docs/software-engineering-policies/OpenSourceContribution/OpenSourceContributionPolicy.md
- docs/software-engineering-policies/OpenSourceUse/OpenSourceUsePolicy.md
- docs/software-engineering-policies/ThirdPartyLicensing/ThirdPartyLicensingPolicy.md
> replace word 'whitelist'

- docs/software-engineering-policies/development-principles.md
Copied our development principles from https://design.ukho.dev/principles/development/
> Nev   move design principles into docs repo

- docs/software-engineering-policies/InclusiveLanguage/InclusiveLanguagePolicy.md
- docs/software-engineering-policies/README.md
> Add an Inclusive Language Policy

- docs/software-engineering-policies/engineering-team.md
I've added some text about our teams and how we work
> Nev add life at uk

- docs/software-engineering-policies/InclusiveLanguage/InclusiveLanguagePolicy.md
I don't think we need to go through an issue as you already raised this one in the Yammer thread @dynamictulip.
> Add disability bias as per community suggestion

- docs/software-engineering-policies/InclusiveLanguage/InclusiveLanguagePolicy.md
Clarify that the draft submitted to the IETF has not yet been adopted by any working group.
> Reword inclusive language further reading

- README.md
- docs/software-engineering-policies/SecureDevelopment/SecurityChampion.md
> Nev create rich readme

- docs/using-github/readme.md
- Nothing major, just a little tidy
> Update GitHub Guidance

- docs/software-engineering-policies/SecureDevelopment/SecureDevelopmentPolicy.md
- docs/software-engineering-policies/SecureDevelopment/SecurityChampionResponsibilities.md
- Brought Secure Development in-line with the version on SharePoint.
- Renamed SecurityChampion.md to SecurityChampionResponsibilities.md.
- Markdown formatting.
> Secure policy updates

- quality-assurance/web-accessibility-testing.md
- quality-assurance/web-accessibility.md
Updated our accessibility content to allow us to state test approach requirements for projects/third-parties.
> Update a11y guidance with project testing page

- software-engineering-policies/NFRs/NFRPolicy.md
- software-engineering-policies/README.md
- Add policy around NFRs following consultations with the leads and architecture practice
> Add NFR policy

- software-engineering-policies/Logging/LoggingPolicy.md
This is the result of a dedicated working group that formed to discuss and create a new logging policy for Software Engineering.
> Add SE logging policy

- quality-assurance/README.md
Updated navigation as per review
> Update QA README

- .github/workflows/markdown-ci.yml
- software-engineering-policies/PairProgramming/PairProgrammingPolicy.md
Proposed update to Pair Programming policy which would mitigate the need for each team to maintain their own policy.
> Update Pair Programming Policy

- software-engineering-policies/CodingStandards/CssCodingStandards.md
- software-engineering-policies/CodingStandards/HtmlCodingStandards.md
Migrate the CSS and HTML coding standards from the old document library QWP668.04 to GitHub.
https://ukho.sharepoint.com/:w:/r/sites/docstore-prd/_layouts/15/Doc.aspx?sourcedoc=%7BB3E9B848-4760-4E2C-BA96-5F392E352F08%7D&file=QWP668.04.docx&action=default&mobileredirect=true
> Migrate the CSS and HTML coding standards from the old document library

- software-engineering-policies/Pipelines/Baseline_Policy.md
Added some documentation recommending resource approval for deployment pipelines
> Update deployment doc with approval recommendation

- software-engineering-policies/README.md
- software-engineering-policies/SecureDevelopment/SecureDevelopmentPolicy.md
… software engineering policy index
> Added links to the Security Concerns and CVSS Scoring Guidance

- quality-assurance/test-strategy.md
Quick patch to change link from testing-principles.md to point to ukho-quality-charter.md for automation policy instead.
> Update broken link

- quality-assurance/manual-test-scripts.md
Added a new page to provide policy on using AzDo for manual test scripts
> Manual test scripts guidance

- software-engineering-policies/CloudDevelopment/CloudDevelopmentPolicy.md
First draft of wording for Purpose of this Policy
> Purpose of this policy

- software-engineering-policies/CloudDevelopment/CloudDevelopmentPolicy.md
First draft for Scope of this Policy
> WIP - Scope of this policy

- software-engineering-policies/CloudDevelopment/CloudDevelopmentPolicy.md
Initial Draft of Revision History
> Revision history

- software-engineering-policies/CloudDevelopment/CloudDevelopmentPolicy.md
Remove duplication of guidelines, but leave earmarked initials for further expansion
> fix: tidy up duplication

- software-engineering-policies/TechnologyGovernance/TechnologyGovernance.md
Correcting the rings on the tech radar referenced by the tech governance policy, and some rewording for clarification.
Relates to:
* <https://github.com/UKHO/tech-radar/issues/582>
* <https://github.com/UKHO/tech-radar/issues/516>
> Correcting the rings on the tech radar referenced by the tech governance policy

- software-engineering-policies/CloudDevelopment/CloudDevelopmentPolicy.md
Add link to draft observabilty policy and update docs to reflect recent "budgetary uplift" for APM and Elasticsearch.
> Observability

- software-engineering-policies/CodingStandards/PythonCodingStandards.md
(Migration from old policies repository: https://ukho.sharepoint.com/sites/Technology/SE/SEWiki/Pages/Python%20Coding%20Standards.aspx)
> Adding Python Coding Standards

- software-engineering-policies/CloudDevelopment/CloudDevelopmentPolicy.md
Introduced a new "Centralized Secrets Management" section under "Secrets Management" with detailed guidelines on:
- Access Control: Use Azure RBAC and Key Vault Access Policies.
- Network Security: Enable Private or Service Endpoints.
- Secret Rotation and Expiration: Automate renewal and alerting.
- Audit and Monitoring: Enable and monitor access logs.
- Secure Application Integration: Use Managed Identities, remove hardcoded secrets.
- Compliance: Align with UK government standards.
- Exceptions: Require documented approval and risk assessment.
> Add Policy for Secrets Management

- quality-assurance/performance-test-checklist.md
Small change so that it suggests using Grafana cloud rather than setting up an influx instance
> Now references Grafana cloud
